In [2]:
import numpy as np

In [3]:
y_datapath = '/home/jihoon/workspace/Demo_binary/data/processed/260602_sub1_hjlee_raw/y.npy'
y01_datapath = '/home/jihoon/workspace/Demo_binary/data/processed/260602_sub1_hjlee_raw/y_01.npy'
y02_datapath = '/home/jihoon/workspace/Demo_binary/data/processed/260602_sub1_hjlee_raw/y_02.npy'
y03_datapath = '/home/jihoon/workspace/Demo_binary/data/processed/260602_sub1_hjlee_raw/y_03.npy'
y04_datapath = '/home/jihoon/workspace/Demo_binary/data/processed/260602_sub1_hjlee_raw/y_04.npy'


In [4]:
y = np.load(y_datapath)
y01 = np.load(y01_datapath)
y02 = np.load(y02_datapath)
y03 = np.load(y03_datapath)
y04 = np.load(y04_datapath)

In [5]:
print(y[:10])
print(y01[:10])
print(y02[:10])
print(y03[:10])
print(y04[:10])

[3 4 2 0 0 4 0 2 2 2]
[1 1 1 0 0 1 0 1 1 1]
[1 1 0 0 0 1 0 0 0 0]
[0 1 1 0 0 1 0 1 1 1]
[1 0 1 0 0 0 0 1 1 1]


In [6]:
print("y shape:", y.shape)

y shape: (500,)


In [8]:
x_datapath = '/home/jihoon/workspace/Demo_binary/data/processed/260602_sub1_hjlee_raw/X_eeg_raw.npy'
x_cov_datapath = '/home/jihoon/workspace/Demo_binary/data/processed/260602_sub1_hjlee_raw/X_eeg_cov.npy'

x = np.load(x_datapath)
x_cov = np.load(x_cov_datapath)

print("x shape:", x.shape)
print("x_cov shape:", x_cov.shape)

x shape: (500, 63, 8501)
x_cov shape: (500, 8, 16, 16)
